In [2]:
import numpy as np

In [5]:
l=[]
for i in range(1,5):
    int_1=input("enter :")
    l.append(int_1)
    
print(np.array(l))
#mthis is a string array

enter : 1
enter : 3
enter : 6
enter : 7


['1' '3' '6' '7']


In [13]:
l=[]
for i in range(1,5):
    int_1=int(input("enter :"))
    l.append(int_1)
    
print(np.array(l))
#this is a Interger array

enter : 34
enter : 45
enter : 65
enter : 64


[34 45 65 64]


In [17]:
arr=np.array([[1,2,3,4],[4,3,2,1]])
print("your array is ",arr.ndim,"Dimen")

your array is  2 Dimen


In [18]:
arr1=np.array([[[2,4,5,6,8],[32,43,23,54,65],[3,6,3,6,7]]])
print("Your array is ",arr1.ndim,"Dimen")

Your array is  3 Dimen


In [20]:
arr3=np.array([1,2,34,54,54],ndmin=10)
print("your array is ",arr3);
print("your arrya ",arr3.ndim,"Dimen")

your array is  [[[[[[[[[[ 1  2 34 54 54]]]]]]]]]]
your arrya  10 Dimen


In [28]:
# array filled with 0's
arr_zero=np.zeros(4);
print("this is your zero array and ",arr_zero.ndim," one Dimen")
print(arr_zero)

this is your zero array and  1  one Dimen
[0. 0. 0. 0.]


In [29]:
# array filled with 0's
arr_zero=np.zeros((3,4));
print("this is your zero array and ",arr_zero.ndim," Dimen")
print(arr_zero)

this is your zero array and  2  Dimen
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
# array filled with 0's
arr_zero=np.zeros(((4,3,4)));
print("this is your zero array and ",arr_zero.ndim," Dimen")
print(arr_zero)

this is your zero array and  3  Dimen
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
